### ISSUE TITLE
trying to get the code down using Auto code.

### ISSUE THREAD

**Issue by izzybear666** [kwsch/PKHeX.Discord#3]
Bot was working with $trade but now its not doing anything soo I'm confused. In sysbot Pokémon i changed a few things that were necessary but idk why bots not working.            SaveError: Function definition error (functions/events/discord/command-1.js)
This experimental syntax requires enabling one of the following parser plugin(s): 'jsx, flow, typescript' (1:0)

Error: Function definition error (functions/events/discord/command-1.js)
This experimental syntax requires enabling one of the following parser plugin(s): 'jsx, flow, typescript' (1:0)
    at FileReader.<anonymous> (https://autocode.com/compile/1b1890/script.js:1:977384)
    at FileReader.sentryWrapped (https://browser.sentry-cdn.com/5.16.1/bundle.min.js:2:44808)

The JSON output of the error is below.
{
  "error": {
    "type": "SaveError",
    "message": "Function definition error (functions/events/discord/command-1.js)\nThis experimental syntax requires enabling one of the following parser plugin(s): 'jsx, flow, typescript' (1:0)"
  }
}          This is my error im getting.

**Comment by kwsch** [comment]
Unrelated to this repo. This bot has nothing to do with trading.
